#
# Module manifest for module 'EntraAppReg'
#
# Generated by: Your Name
#
# Generated on: 5/13/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'EntraAppReg.psm1'

# Version number of this module.
ModuleVersion = '0.2.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '74c10163-5323-43e0-8f18-a8bf93dbb479'

# Author of this module
Author = 'Josh'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) Josh. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell module for managing Entra ID app registrations'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.0'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Applications'; ModuleVersion = '2.25.0'; }, 
               @{ModuleName = 'Microsoft.Graph.Authentication'; ModuleVersion = '2.25.0'; })

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    # Original functions
    'Get-EntraKnownServicePrincipal'
    'Update-EntraKnownServices'
    
    # Normalized storage functions
    'Get-EntraNormalizedKnownServicePrincipal'
    'Update-EntraNormalizedKnownServices'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'EntraAppReg.psm1'
    'EntraAppReg.psd1'
    'Config\KnownServices.json'
    'Config\KnownServicesIndex.json'
    'Config\ServicePrincipals.json'
    'Config\PermissionDefinitions.json'
    'Config\ServicePermissionMappings.json'
    'Config\CommonPermissions.json'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Entra', 'AppRegistration', 'Microsoft Graph'

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/yourusername/EntraAppReg'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
v0.2.0
- Added normalized storage format to improve performance and reduce storage requirements
- Added new functions: Get-EntraNormalizedKnownServicePrincipal, Update-EntraNormalizedKnownServices
- Updated existing functions to support both legacy and normalized storage formats
- Added UseNormalizedStorage parameter to Get-EntraKnownServicePrincipal and Update-EntraKnownServices
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

